apiVersion: v1
kind: Secret
metadata:
  name: sim-bank-secret
  namespace: sim-bank
type: Opaque
stringData:
  DB_USERNAME: corebank
  DB_PASSWORD: corebank_demo
  OAUTH2_CLIENT_ID: moneybank-service
  OAUTH2_CLIENT_SECRET: moneybank-secret
  VAULT_DEV_ROOT_TOKEN_ID: sim-bank-root-token
  ORACLE_PASSWORD: oracle_demo
  APP_USER: corebank
  APP_USER_PASSWORD: corebank_demo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres_password
  POSTGRES_DB: common_db
