-- ============================================================
-- V2 – RBAC Schema (Users, Roles, Permissions)
-- ============================================================

CREATE TABLE users (
    id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR2(50)  NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_users         PRIMARY KEY (id),
    CONSTRAINT uk_username      UNIQUE (username)
);

CREATE TABLE roles (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    role_code   VARCHAR2(50)  NOT NULL,
    role_name   VARCHAR2(100) NOT NULL,
    status      BOOLEAN       NOT NULL,
    CONSTRAINT pk_roles         PRIMARY KEY (id),
    CONSTRAINT uk_role_code     UNIQUE (role_code)
);

CREATE TABLE permissions (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    menu_code   VARCHAR2(50)  NOT NULL,
    action      VARCHAR2(20)  NOT NULL,
    description VARCHAR2(255),
    CONSTRAINT pk_permissions   PRIMARY KEY (id),
    CONSTRAINT uk_menu_action   UNIQUE (menu_code, action)
);

CREATE TABLE user_roles (
    user_id     NUMBER(19,0)  NOT NULL,
    role_id     NUMBER(19,0)  NOT NULL,
    CONSTRAINT pk_user_roles    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user       FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ur_role       FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE role_permissions (
    role_id       NUMBER(19,0)  NOT NULL,
    permission_id NUMBER(19,0)  NOT NULL,
    CONSTRAINT pk_role_perms    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT fk_rp_perm       FOREIGN KEY (permission_id) REFERENCES permissions (id)
);
