CREATE TABLE outbox_event (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR2(64) NOT NULL,
    aggregate_type VARCHAR2(64) NOT NULL,
    aggregate_id VARCHAR2(64) NOT NULL,
    event_type VARCHAR2(128) NOT NULL,
    schema_version VARCHAR2(16) NOT NULL,
    payload CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    attempt_count NUMBER(10,0) NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_error_code VARCHAR2(64),
    version NUMBER NOT NULL,
    CONSTRAINT uk_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX ix_outbox_pending ON outbox_event (published_at, next_attempt_at);
CREATE INDEX ix_outbox_aggregate ON outbox_event (aggregate_type, aggregate_id);
