-- ============================================================
-- V1 – Initial Schema (Baseline for Corebank Service)
-- ============================================================

-- ============================================================
-- 1. CORE BANKING ENTITIES
-- ============================================================

-- Customers
CREATE TABLE customers (
    cif_number   VARCHAR2(20)  NOT NULL,
    national_id  VARCHAR2(20),
    full_name    VARCHAR2(100),
    phone_number VARCHAR2(20),
    email        VARCHAR2(100),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_customers            PRIMARY KEY (cif_number),
    CONSTRAINT uk_customer_national_id UNIQUE (national_id)
);

-- Account number sequence (prefix "10" + 10 digits → 12-char account number)
CREATE SEQUENCE account_number_seq
    START WITH 1000000000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Bank cards
CREATE TABLE bank_cards (
    id          VARCHAR2(36)  NOT NULL,
    card_number VARCHAR2(16)  NOT NULL,
    account_id  VARCHAR2(36)  NOT NULL,
    status      VARCHAR2(20)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_bank_cards    PRIMARY KEY (id),
    CONSTRAINT uk_card_number   UNIQUE (card_number)
);

-- ============================================================
-- 2. RBAC SCHEMA (Users, Roles, Permissions)
-- ============================================================

CREATE TABLE users (
    id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR2(50)  NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_users         PRIMARY KEY (id),
    CONSTRAINT uk_username      UNIQUE (username)
);

CREATE TABLE roles (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    role_code   VARCHAR2(50)  NOT NULL,
    role_name   VARCHAR2(100) NOT NULL,
    status      BOOLEAN       NOT NULL,
    CONSTRAINT pk_roles         PRIMARY KEY (id),
    CONSTRAINT uk_role_code     UNIQUE (role_code)
);

CREATE TABLE permissions (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    menu_code   VARCHAR2(50)  NOT NULL,
    action      VARCHAR2(20)  NOT NULL,
    description VARCHAR2(255),
    CONSTRAINT pk_permissions   PRIMARY KEY (id),
    CONSTRAINT uk_menu_action   UNIQUE (menu_code, action)
);

CREATE TABLE user_roles (
    user_id     NUMBER(19,0)  NOT NULL,
    role_id     NUMBER(19,0)  NOT NULL,
    CONSTRAINT pk_user_roles    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user       FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ur_role       FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE role_permissions (
    role_id       NUMBER(19,0)  NOT NULL,
    permission_id NUMBER(19,0)  NOT NULL,
    CONSTRAINT pk_role_perms    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT fk_rp_perm       FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

-- ============================================================
-- 3. IDEMPOTENCY RECORDS
-- ============================================================

CREATE TABLE idempotency_record (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR2(64) NOT NULL,
    operation VARCHAR2(64) NOT NULL,
    idempotency_key VARCHAR2(64) NOT NULL,
    request_hash VARCHAR2(64) NOT NULL,
    transaction_id VARCHAR2(64),
    workflow_id VARCHAR2(64),
    status VARCHAR2(32) NOT NULL,
    response_code VARCHAR2(32),
    response_snapshot VARCHAR2(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    version NUMBER NOT NULL,
    CONSTRAINT uk_idem_customer_operation_key UNIQUE (customer_id, operation, idempotency_key),
    CONSTRAINT uk_idem_transaction_id UNIQUE (transaction_id)
);

CREATE INDEX ix_idem_workflow_id ON idempotency_record (workflow_id);
CREATE INDEX ix_idem_expires_at ON idempotency_record (expires_at);

-- ============================================================
-- 4. TRANSACTIONAL OUTBOX
-- ============================================================

CREATE TABLE outbox_event (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR2(64) NOT NULL,
    aggregate_type VARCHAR2(64) NOT NULL,
    aggregate_id VARCHAR2(64) NOT NULL,
    event_type VARCHAR2(128) NOT NULL,
    schema_version VARCHAR2(16) NOT NULL,
    payload CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    attempt_count NUMBER(10,0) NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_error_code VARCHAR2(64),
    version NUMBER NOT NULL,
    CONSTRAINT uk_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX ix_outbox_pending ON outbox_event (published_at, next_attempt_at);
CREATE INDEX ix_outbox_aggregate ON outbox_event (aggregate_type, aggregate_id);

-- ============================================================
-- 5. EVENT STORE (Write Side)
-- ============================================================

-- Bảng gốc của Event Sourcing: append-only, không bao giờ UPDATE/DELETE.
-- Ràng buộc UNIQUE (aggregate_id, version) đóng vai trò Optimistic Lock,
-- thay thế hoàn toàn SELECT ... FOR UPDATE của V1.
CREATE TABLE domain_events (
    event_id        VARCHAR2(50)  NOT NULL,
    aggregate_id    VARCHAR2(50)  NOT NULL,
    aggregate_type  VARCHAR2(50)  NOT NULL,
    version         NUMBER(19)    NOT NULL,
    event_type      VARCHAR2(100) NOT NULL,
    payload         CLOB          NOT NULL,
    metadata        CLOB,
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_domain_events     PRIMARY KEY (event_id),
    CONSTRAINT uq_aggregate_version UNIQUE (aggregate_id, version)
);

-- Snapshot: lưu trạng thái tổng hợp sau mỗi 50 sự kiện.
-- Khi load aggregate, chỉ cần replay từ version snapshot trở đi.
CREATE TABLE aggregate_snapshots (
    aggregate_id    VARCHAR2(50)  NOT NULL,
    aggregate_type  VARCHAR2(50)  NOT NULL,
    version         NUMBER(19)    NOT NULL,
    payload         CLOB          NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_aggregate_snapshots PRIMARY KEY (aggregate_id)
);

-- ============================================================
-- 6. READ SIDE PROJECTIONS (CQRS)
-- ============================================================

-- account_view: nguồn sự thật cho chiều Query (Mobile App, Dashboard).
-- Không bao giờ dùng bảng này để validate Command.
-- Cột last_event_version là chìa khóa chống xử lý event trùng lặp (Idempotency).
CREATE TABLE account_view (
    account_id            VARCHAR2(50)  NOT NULL,
    account_number        VARCHAR2(20)  NOT NULL,
    customer_id           VARCHAR2(20)  NOT NULL,
    currency              VARCHAR2(3)   NOT NULL,
    actual_balance        NUMBER(19, 4) DEFAULT 0 NOT NULL,
    available_balance     NUMBER(19, 4) DEFAULT 0 NOT NULL,
    status                VARCHAR2(20)  NOT NULL,
    last_event_version    NUMBER(19)    DEFAULT 0 NOT NULL,
    last_updated_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_account_view PRIMARY KEY (account_id)
);

CREATE INDEX ix_account_view_customer ON account_view (customer_id);

-- transaction_history_view: sao kê hiển thị cho User (Statement).
-- balance_after cho phép User thấy số dư sau mỗi giao dịch — đặc trưng ngân hàng.
CREATE TABLE transaction_history_view (
    id            VARCHAR2(50)  NOT NULL,
    account_id    VARCHAR2(50)  NOT NULL,
    direction     VARCHAR2(6)   NOT NULL,
    amount        NUMBER(19, 4) NOT NULL,
    currency      VARCHAR2(3)   NOT NULL,
    balance_after NUMBER(19, 4) NOT NULL,
    event_type    VARCHAR2(100) NOT NULL,
    description   VARCHAR2(255),
    occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_txhv PRIMARY KEY (id)
);

CREATE INDEX ix_txhv_account_date ON transaction_history_view (account_id, occurred_at DESC);

-- transfer_view: nguồn dữ liệu cho Read side và Idempotency check của Transfer
CREATE TABLE transfer_view (
    transfer_id            VARCHAR2(50)   NOT NULL,
    request_hash           VARCHAR2(64)   NOT NULL,
    source_account_id      VARCHAR2(50),
    destination_account_id VARCHAR2(50),
    amount                 NUMBER(19, 4)  NOT NULL,
    currency               VARCHAR2(3)    NOT NULL,
    description            VARCHAR2(255),
    status                 VARCHAR2(20)   NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_transfer_view PRIMARY KEY (transfer_id)
);

CREATE INDEX ix_transfer_view_status_updated ON transfer_view (status, updated_at);


-- ============================================================
-- 7. TRANSFER PROPOSALS (U-06: Transfer Command & State Machine)
-- ============================================================
--
-- Bảng này lưu Transfer Proposal — aggregate root của luồng chuyển tiền 2 bước.
--
-- State Machine:
--   PENDING → VALIDATING → CONFIRMED (terminal)
--           → REJECTED (terminal)
--   PENDING → VALIDATING → FAILED (terminal)
--
-- Idempotency: uk_proposal_idempotency_key bảo đảm mỗi ý định chỉ tạo 1 proposal.
-- OCC: cột version (Oracle optimistic locking) chặn concurrent confirm.
-- ============================================================

CREATE TABLE transfer_proposals (
    -- Định danh
    id                      VARCHAR2(36)    NOT NULL,
    initiator_customer_id   VARCHAR2(64)    NOT NULL,   -- CIF từ identity context

    -- Nghiệp vụ
    source_account_id       VARCHAR2(36)    NOT NULL,
    destination_account_id  VARCHAR2(36)    NOT NULL,
    amount                  NUMBER(19, 2)   NOT NULL,
    currency                VARCHAR2(3)     NOT NULL,
    idempotency_key         VARCHAR2(64)    NOT NULL,
    description             VARCHAR2(255),

    -- Trạng thái state machine
    status                  VARCHAR2(20)    NOT NULL,   -- PENDING/VALIDATING/CONFIRMED/FAILED/REJECTED

    -- Kết quả từ Corebank (null cho đến khi CONFIRMED)
    corebank_transaction_id VARCHAR2(64),

    -- Lý do thất bại/từ chối (null khi PENDING/CONFIRMED)
    failure_reason          VARCHAR2(255),

    -- Audit
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Optimistic Concurrency Control
    version                 NUMBER(19, 0)   DEFAULT 0 NOT NULL,

    -- Constraints
    CONSTRAINT pk_transfer_proposals            PRIMARY KEY (id),
    CONSTRAINT uk_proposal_idempotency_key      UNIQUE (idempotency_key),
    CONSTRAINT chk_proposal_amount_positive     CHECK (amount > 0),
    CONSTRAINT chk_proposal_accounts_different  CHECK (source_account_id <> destination_account_id),
    CONSTRAINT chk_proposal_status              CHECK (status IN (
        'PENDING', 'VALIDATING', 'CONFIRMED', 'FAILED', 'REJECTED'
    ))
);

-- Index cho query theo account (source hoặc destination)
CREATE INDEX idx_proposal_source    ON transfer_proposals (source_account_id, created_at);
CREATE INDEX idx_proposal_dest      ON transfer_proposals (destination_account_id, created_at);

-- Index cho query theo status (ví dụ tìm PENDING để reconciliation)
CREATE INDEX idx_proposal_status    ON transfer_proposals (status, created_at);

-- Index cho query theo người khởi tạo
CREATE INDEX idx_proposal_initiator ON transfer_proposals (initiator_customer_id, created_at);
