CREATE TABLE idempotency_record (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR2(64) NOT NULL,
    operation VARCHAR2(64) NOT NULL,
    idempotency_key VARCHAR2(64) NOT NULL,
    request_hash VARCHAR2(64) NOT NULL,
    transaction_id VARCHAR2(64),
    workflow_id VARCHAR2(64),
    status VARCHAR2(32) NOT NULL,
    response_code VARCHAR2(32),
    response_snapshot VARCHAR2(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    version NUMBER NOT NULL,
    CONSTRAINT uk_idem_customer_operation_key UNIQUE (customer_id, operation, idempotency_key),
    CONSTRAINT uk_idem_transaction_id UNIQUE (transaction_id)
);

CREATE INDEX ix_idem_workflow_id ON idempotency_record (workflow_id);
CREATE INDEX ix_idem_expires_at ON idempotency_record (expires_at);
