apiVersion: v1
kind: ConfigMap
metadata:
  name: sim-bank-common
  namespace: sim-bank
data:
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/simulation-bank
  COREBANK_URL: http://corebank:8180
  MONEY_BANK_URL: http://money-bank:8181
  CMS_BACKEND_URL: http://cms:8182
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
  OTEL_LOGS_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4318/v1/logs
